### Martin Muga
### Email: martinmuga04@gmail.com
#### Solutions for question 3

For question 3, i used LSTM  RNN to train my prediction model.Basic neural nets such as RNN are faced with the vanishing gradient descend problems and LSTM solves this problem because it has a hidden state, and a memory cell with three gates namely forgotten, read and input gate.
Given a sequence of inputs, it will compute a sequence of hidden states.
I deceided to use str.comtains to filter out the payments_receipts that had the sequence MK in them. After that, I created a dataframe that contains only the payment receipts with the sequence MK and turned it into a csv file with the name data.csv.
Since this is a NLP problem, I used only the payment receipt row to train the model to predict the next character given an input of a sequence of charaters.
I therefore converted the payment_receipt row in the dataframe into a list and named it b and joined it with space. I then converted the list b into a textfile name listfile.txt

In [1]:
#Load the data using pandas
import pandas as pd
df = pd.read_csv('train_revised.csv')
df

ride_id seat_number payment_method payment_receipt travel_date  \
0         1442         15A          Mpesa      UZUEHCBUSO    17-10-17   
1         5437         14A          Mpesa      TIHLBUSGTE    19-11-17   
2         5710          8B          Mpesa      EQX8Q5G19O    26-11-17   
3         5777         19A          Mpesa      SGP18CL0ME    27-11-17   
4         5778         11A          Mpesa      BM97HFRGL9    27-11-17   
...        ...         ...            ...             ...         ...   
51640    13826          9B          Mpesa      8V2XDDZR6V    20-04-18   
51641    13809         18A          Mpesa      4PEBSVJSNK    20-04-18   
51642    13809         17A          Mpesa      LVN64LZDNN    20-04-18   
51643    13796         16B          Mpesa      REYBSKTYWN    20-04-18   
51644    14304           7          Mpesa      AQN7FBUSGP    14-11-17   

      travel_time travel_from travel_to car_type  max_capacity  
0            7:15      Migori   Nairobi      Bus            49  
1            7:12      Migori   Nairobi      Bus            49  
2            7:05      Keroka   Nairobi      Bus            49  
3            7:10    Homa Bay   Nairobi      Bus            49  
4            7:12      Migori   Nairobi      Bus            49  
...           ...         ...       ...      ...           ...  
51640        8:00      Awendo   Nairobi      Bus            49  
51641        8:00      Migori   Nairobi      Bus            49  
51642        8:00      Migori   Nairobi      Bus            49  
51643        7:08      Awendo   Nairobi      Bus            49  
51644        5:10       Kisii   Nairobi      Bus            49  

[51645 rows x 10 columns]

In [2]:
print(df.columns.tolist())

['ride_id', 'seat_number', 'payment_method', 'payment_receipt', 'travel_date', 'travel_time', 'travel_from', 'travel_to', 'car_type', 'max_capacity']


In [3]:
#Filter payment receipts to only contain those with the sequence MK

new = df['payment_receipt'].str.contains('MK') 
df[new]

ride_id seat_number payment_method payment_receipt travel_date  \
47        5801          1X          Mpesa      TBJMRMKQLJ    19-04-18   
99        5838           9          Mpesa      LYMKG9DII7    17-04-18   
141       5861          3A          Mpesa      7BMTKUMKJZ    15-04-18   
172       5868          1X          Mpesa      OMKHFVAGHD    14-04-18   
369       6015           1          Mpesa      VUA7IXPMKP    05-04-18   
...        ...         ...            ...             ...         ...   
50966    13739          5A          Mpesa      0PD1FOMKSR    19-04-18   
51104    13747          3A          Mpesa      FMKNNJGZCF    19-04-18   
51252    13765         21A          Mpesa      OYKMKRNAXR    19-04-18   
51355    13786          6B          Mpesa      EWMKKT9H11    20-04-18   
51624    13813          7B          Mpesa      CTFSLKISMK    20-04-18   

      travel_time travel_from travel_to car_type  max_capacity  
47           5:20       Kisii   Nairobi  shuttle            11  
99           6:30       Kisii   Nairobi  shuttle            11  
141         19:04       Kisii   Nairobi      Bus            49  
172          5:20       Kisii   Nairobi  shuttle            11  
369          5:10       Kisii   Nairobi  shuttle            11  
...           ...         ...       ...      ...           ...  
50966        8:00      Awendo   Nairobi      Bus            49  
51104        7:09    Homa Bay   Nairobi      Bus            49  
51252        7:14       Rongo   Nairobi      Bus            49  
51355       19:07      Sirare   Nairobi      Bus            49  
51624        7:05      Ndhiwa   Nairobi      Bus            49  

[499 rows x 10 columns]

In [4]:
#Save the payment_receipts with sequence MK to a new csv file
df[new].to_csv('data.csv')
data = pd.read_csv('data.csv')
data.head()

Unnamed: 0  ride_id seat_number payment_method payment_receipt travel_date  \
0          47     5801          1X          Mpesa      TBJMRMKQLJ    19-04-18   
1          99     5838           9          Mpesa      LYMKG9DII7    17-04-18   
2         141     5861          3A          Mpesa      7BMTKUMKJZ    15-04-18   
3         172     5868          1X          Mpesa      OMKHFVAGHD    14-04-18   
4         369     6015           1          Mpesa      VUA7IXPMKP    05-04-18   

  travel_time travel_from travel_to car_type  max_capacity  
0        5:20       Kisii   Nairobi  shuttle            11  
1        6:30       Kisii   Nairobi  shuttle            11  
2       19:04       Kisii   Nairobi      Bus            49  
3        5:20       Kisii   Nairobi  shuttle            11  
4        5:10       Kisii   Nairobi  shuttle            11

In [5]:
#Convert payment_receipt row into a lis then into a txt file
a = list(data['payment_receipt'])
# converting list into string and then joining it with space
b = ' '.join(str(e) for e in a)
  
# printing result
print(b)

#Convert list b to txt file
with open('listfile.txt', 'w') as filehandle:
    for listitem in b:
        filehandle.write('%s\n' % listitem)

TBJMRMKQLJ LYMKG9DII7 7BMTKUMKJZ OMKHFVAGHD VUA7IXPMKP MKWNS24S9N PBPQWRMK3D U4E3MKPFL3 DMKAARIPUX VOXSQ8OMKY WHS1NZMKQV VP4IVMK9S9 ZJNMI9MKYF MKNF2KD0U2 EJ6BTPEHMK UCMKDTBA9F MK1VCQJUUU PMK79CLMAA RMK65BW48J NIKOEYJMKO FDU9SMKGK1 PYNMKXBHIJ NDPMKLM9BG ERQUWMK1BR MDMKTXUUWJ PHMKZNKFRO 88MK4L2NE7 YMKFVDLSLD HMKHQEROZV EATQMK9INK MKZOPZOJWF JVRJXMKUO2 QWVFTGSMKD KMKMSFGZAH DOKM7JMKM1 GBCGMKFWDU NLMKBO8KBZ RW5MKYRRJO ELDMKHZJAS ALDMWMKBRK CIUGFMK3OJ C0VJIMKHE5 B6SGUDHMK6 AWUSAFJMKI ZJAFPXMKMK GJMK8X8VOB Y6CREMRMKM APYPOOMMKI PIOEZAXWMK SVA4MKKMZD PSRAWVMKCM MKZFPF9OQL WPHNU98MK9 0XQZMKCWSR 0KULGYMKZC AOON9GMKFI 4OCS2GRNMK CIJJOMKBIR OMKXAKHKYG ELJFWIMK0I 5MKG7KRNPP EE71GMK1BY UYXMKYGVSS UIJSPI3MK2 MK1XTRHG57 9AYMKFEF9S XNHCXRSMK3 I1BMKHFRZP PLHMKBWDBF XP3VSBOMKC MKT8CE7ALC M8DEMKYYRU ZATKCMQMKW KBKMKOQZDB IZY79GMKKI FCUYITB3MK ZMKITPHVBT MKENM3UIN8 GB7CFMK2FJ RHM2OAMKPD AWOP33MKCL RXYGV4MK3D GBHLMKILMV SYPKLLOHMK 6RGQTG1MK8 ETUGC8MK59 EMT3QNMK2T YL4HWMKQVL MKR0C6SCOI LMRMKRL5BP FCZEUGMKGO

In [6]:
#Load the txt file into ascii then covert it to lower text
with open('listfile.txt', 'r') as f:
    data = f.read()
    data = data.lower()
    data = data.replace('\n', ' ')
    data = data.replace('\r', ' ')
    data = data.replace('\t', ' ')
    data = data.replace('  ', ' ')
#filename = "listfile.txt"
#raw_text = open(filename, 'r', encoding='utf-8').read()
#raw_text = raw_text.lower()

# create mapping of unique chars to integers
chars = sorted(list(set(data)))

char_to_int = dict((c, i) for i, c in enumerate(chars))

In [7]:
#Summary of laoded data
print('Total Characters: ', len(data))
print('Unique Characters: ', len(chars))
print('Total Vocabulary: ', len(chars))
print('Unique Vocabulary: ', len(chars))

#n_chars = len(data)
#n_vocab = len(chars)
#print("Total Characters: ", n_chars)
#print( "Total Vocab: ", n_vocab)

Total Characters:  10478
Unique Characters:  37
Total Vocabulary:  37
Unique Vocabulary:  37


In [8]:
# prepare the dataset of input to output pairs encoded as integers
seq_length = 100
dataX = []
dataY = []
for i in range(0, len(data) - seq_length, 1):
	seq_in = data[i:i + seq_length]
	seq_out = data[i + seq_length]
	dataX.append([char_to_int[char] for char in seq_in])
	dataY.append(char_to_int[seq_out])
n_patterns = len(dataX)
print("Total Patterns: ", n_patterns)



Total Patterns:  10378


In [9]:
import numpy as np
from keras.utils import np_utils


# reshape X to be [samples, time steps, features]

X = np.reshape(dataX, (n_patterns, seq_length, 1))
# normalize
X = X / float(len(chars))


# one hot encode the output variable
y = np_utils.to_categorical(dataY)

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.callbacks import ModelCheckpoint

# define the LSTM model
model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='accuracy')

In [17]:
# define the checkpoint
filepath="weights-improvement-{epoch:02d}-{loss:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

In [18]:
#Train the model
model.fit(X, y, epochs=3, batch_size=128, callbacks=callbacks_list)

Epoch 1/3
82/82 [==============================] - ETA: 0s - loss: 2.4055 - accuracy: 0.5174
Epoch 00001: loss improved from inf to 2.40550, saving model to weights-improvement-01-2.4055.hdf5
82/82 [==============================] - 66s 760ms/step - loss: 2.4055 - accuracy: 0.5174
Epoch 2/3
82/82 [==============================] - ETA: 0s - loss: 2.2204 - accuracy: 0.5238
Epoch 00002: loss improved from 2.40550 to 2.22041, saving model to weights-improvement-02-2.2204.hdf5
82/82 [==============================] - 63s 770ms/step - loss: 2.2204 - accuracy: 0.5238
Epoch 3/3
82/82 [==============================] - ETA: 0s - loss: 1.9863 - accuracy: 0.5273
Epoch 00003: loss improved from 2.22041 to 1.98629, saving model to weights-improvement-03-1.9863.hdf5
82/82 [==============================] - 63s 767ms/step - loss: 1.9863 - accuracy: 0.5273


In [19]:
#Summary of the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 256)               264192    
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_1 (Dense)             (None, 37)                9509      
                                                                 
Total params: 273,701
Trainable params: 273,701
Non-trainable params: 0
_________________________________________________________________


In [20]:
#Save the model
model.save('model.h5')



#model.save('model.h5')




In [21]:
#Evaluate the model
import numpy as np
from keras.models import load_model
model = load_model('model.h5')
loss, acc = model.evaluate(X, y, verbose=0)
print("Model Accuracy: {:.2f}%".format(acc * 100))
print("Model Loss: {:.2f}".format(loss))


Model Accuracy: 53.43%
Model Loss: 1.91


In [21]:
#Test the next character from the model
import numpy as np
from keras.models import load_model
model = load_model('model.h5')

next_char = (model.predict(X) > 0.5).astype("int32")
print(next_char)








[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [ ]:
#Predict next character in the sequence
import numpy as np
from keras.models import load_model
model = load_model('model.h5')
